#!/bin/sh

case "$1" in
'start')
    /opt/apache2.4/bin/apachectl start
    ;;

'stop')
    /opt/apache2.4/bin/apachectl stop
    ;;

'link')
    ln -s ../init.d/tellme_httpd /etc/rc3.d/S74tellme_httpd
    ln -s ../init.d/tellme_httpd /etc/rc2.d/K40tellme_httpd
    ln -s ../init.d/tellme_httpd /etc/rc1.d/K40tellme_httpd
    ln -s ../init.d/tellme_httpd /etc/rc0.d/K40tellme_httpd
    ln -s ../init.d/tellme_httpd /etc/rcS.d/K40tellme_httpd
    ;;

*)
    echo "Usage: $0 { start | stop | link }"
    exit 1
    ;;

esac

